### ISSUE TITLE
サイトマップを作ろう

### ISSUE THREAD

**Issue by whitepuyo** [whitepuyo/nazopuyo#12]
## 概要
サイトマップを作ろう
## 機能 
なし
## 再現手順と修正方法
なし
## 詳細
パワポで作成したサイトマップをgoogleドライブにうｐ
https://drive.google.com/drive/folders/1vfl8YbnMFdPV1ySvdH1rk8dYbA4JDhDW

**Comment by TanigUhey** [comment]
#5と重複のためClose
